import { createRoot } from 'react-dom/client';
import { useEffect, useMemo, useState } from 'react';
import { Link, Route, Router, Switch } from 'wouter';
import { useHashLocation } from 'wouter/use-hash-location';
import { ArrowUpRight, ArrowRight, Check, ChevronDown, Download, FileText, GitCompareArrows, BookOpen, Search, Sun, Moon, X, Plus, Minus, CircleHelp, ShieldCheck, ListChecks, NotebookPen, MoveUp, MoveDown, ExternalLink, Upload } from 'lucide-react';
import { diffWordsWithSpace } from 'diff';
import raw from './data/policy.json';
import expansion from './data/expansion.json';
import type { Dataset, Notebook, Provision, Review } from '../shared/schema';
import { ACT_URL, CORRECTION_URL, DRAFT_URL, FINAL_URL, REPO, createBrief, csv, filterProvisions, validateNotebook, correctionDraft,mergeCollections,evidenceLinks } from './lib.mjs';
import './style.css';

const data=mergeCollections(raw,expansion) as Dataset;
const families=data.families!;
const icons={desk:BookOpen,compare:GitCompareArrows,sources:FileText,corrections:ListChecks,brief:NotebookPen,contributions:FileText,method:ShieldCheck};
const contributions=data.provisions.filter(p=>p.contribution);
const sourceFamily=(id:string)=>id.startsWith('sgi-')?'sgi':id.startsWith('aig-')?'aig':'dpdp';
function FamilySelect({value,onChange,testid}:{value:string,onChange:(s:string)=>void,testid:string}){return <label className="family-selector">Policy collection<select value={value} onChange={e=>onChange(e.target.value)} data-testid={testid}><option value="All">All three collections</option>{families.map(f=><option key={f.id} value={f.id}>{f.shortTitle}</option>)}</select></label>}
function download(name:string, text:string, type='text/plain;charset=utf-8') {
  const url=URL.createObjectURL(new Blob([text],{type}));
  const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();
  setTimeout(()=>URL.revokeObjectURL(url),3000);
}
function Logo(){return <svg role="img" aria-label="AI Watch India mark" viewBox="0 0 36 36" fill="none"><path d="M7 12h15v18H7zM14 6h15v18H14" stroke="currentColor" strokeWidth="1.8"/><path d="M12 19h5M19 13h5" stroke="currentColor" strokeWidth="1.8"/></svg>}
function Badge({children,kind=''}:{children:React.ReactNode,kind?:string}){return <span className={`badge ${kind}`}>{children}</span>}
function OutLink({href,children,testid}:{href:string,children:React.ReactNode,testid?:string}){return <a href={href} target="_blank" rel="noopener noreferrer" data-testid={testid}>{children}<ArrowUpRight size={14}/></a>}
function App(){
  const [location]=useHashLocation();
  const [theme,setTheme]=useState(()=>window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');
  const [notebook,setNotebook]=useState<Notebook>({version:1,selected:[],reviews:[],title:'Digital policy change brief'});
  const [notice,setNotice]=useState('');
  const [report,setReport]=useState<Provision|null>(null);
  const [reason,setReason]=useState(''),[evidence,setEvidence]=useState('');
  const [reportError,setReportError]=useState('');
  useEffect(()=>{document.documentElement.dataset.theme=theme},[theme]);
  useEffect(()=>{
    const handler=(event:MouseEvent)=>{
      const anchor=(event.target as Element)?.closest<HTMLAnchorElement>('a[download]');
      if(!anchor||anchor.href.startsWith('blob:'))return;
      event.preventDefault();
      fetch(anchor.href).then(async response=>{
        if(!response.ok)throw Error('File unavailable');
        const text=await response.text();
        const name=new URL(anchor.href).pathname.split('/').pop()||'research.txt';
        download(name,text,response.headers.get('content-type')||'text/plain;charset=utf-8');
        setNotice('Research file downloaded.');
      }).catch(()=>setNotice('Download failed. Please retry or retrieve the file from the repository.'));
    };
    document.addEventListener('click',handler);
    return()=>document.removeEventListener('click',handler);
  },[]);
  useEffect(()=>{window.scrollTo({top:0});setNotice('')},[location]);
  useEffect(()=>{if(!report)return;
    document.querySelectorAll('.rail,.body').forEach(el=>el.setAttribute('inert',''));
    const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')setReport(null);if(e.key==='Tab'){
      const controls=Array.from(document.querySelectorAll<HTMLButtonElement>('.modal button,.modal input,.modal textarea,.modal a'));
      const first=controls[0],last=controls[controls.length-1];
      if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}
      if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}
    }};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);document.querySelectorAll('.rail,.body').forEach(el=>el.removeAttribute('inert'));document.querySelector<HTMLButtonElement>('[data-testid="button-propose-correction"]')?.focus()}
  },[report]);
  const toggle=(id:string)=>setNotebook(n=>({...n,selected:n.selected.includes(id)?n.selected.filter(x=>x!==id):[...n.selected,id]}));
  function saveReview(review:Review){setNotebook(n=>({...n,reviews:[...n.reviews,review]}));setNotice('Review saved in this session. Export your notebook to keep it.')}
  const section=location.startsWith('/compare')?'compare':location.startsWith('/sources')?'sources':location.startsWith('/corrections')?'corrections':location.startsWith('/brief')?'brief':location.startsWith('/contributions')?'contributions':location.startsWith('/method')?'method':'desk';
  const nav=[['desk','/','The desk'],['compare','/compare/rule-8','Compare provisions'],['contributions','/contributions','30 contributions'],['sources','/sources','Source library'],['corrections','/corrections','Corrections'],['brief','/brief','Your brief'],['method','/method','Method & limits']];
  return <div className="shell">
    <a className="skip" href="#main" onClick={e=>{e.preventDefault();document.getElementById('main')?.focus()}}>Skip to content</a>
    <aside className="rail">
      <Link href="/" className="brand" data-testid="link-brand"><Logo/><span>AI Watch <b>India</b><small>POLICY CHANGE DESK</small></span></Link>
      <div className="rail-rule"/>
      <p className="rail-label">WORKSPACE</p>
      <nav aria-label="Main navigation">{nav.map(([id,path,label])=>{const Icon=icons[id as keyof typeof icons];return <Link key={id} href={path} className={section===id?'nav active':'nav'} data-testid={`nav-${id}`} aria-current={section===id?'page':undefined}><Icon size={18}/><span>{label}</span>{id==='brief'&&<span className="nav-count">{notebook.selected.length}</span>}</Link>})}</nav>
      <div className="rail-bottom"><span className="status-dot"/>Curated, not a live feed<p>Three collections · India<br/>Expanded 05 Oct 2026</p><OutLink href={REPO} testid="link-repo">Open-source repository</OutLink></div>
    </aside>
    <div className="body">
      <header className="topbar"><div className="crumb">Workspace <span>/</span> {nav.find(x=>x[0]===section)?.[2]}</div><div className="top-actions"><span className="edition">CURATED EDITION 02</span><button className="icon-button" aria-label={`Switch to ${theme==='light'?'dark':'light'} mode`} title="Change theme" data-testid="button-theme" onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</button><Link href="/brief" className="btn small" data-testid="button-open-brief"><NotebookPen size={16}/>Your brief <span>{notebook.selected.length}</span></Link></div></header>
      {notice&&<div className="notice" role="status" data-testid="status-notice">{notice}<button aria-label="Dismiss notification" data-testid="button-dismiss-notice" onClick={()=>setNotice('')}><X size={16}/></button></div>}
      <main id="main" tabIndex={-1}>
      <Switch>
        <Route path="/"><Desk notebook={notebook} toggle={toggle}/></Route>
        <Route path="/compare/:id">{params=><Compare id={params.id} notebook={notebook} toggle={toggle} saveReview={saveReview} report={p=>{setReport(p);setReason('');setEvidence('');setReportError('')}}/>}</Route>
        <Route path="/sources"><Sources/></Route>
        <Route path="/corrections"><Corrections/></Route>
        <Route path="/contributions"><Contributions/></Route>
        <Route path="/brief"><Brief notebook={notebook} setNotebook={setNotebook} notify={setNotice}/></Route>
        <Route path="/method"><Method/></Route>
        <Route><div className="page"><h1>This page is not in the collection.</h1><p>Your notebook is still here. Return to the desk to choose a provision.</p><Link className="btn primary" href="/">Return to the desk</Link></div></Route>
      </Switch>
      </main>
      <footer><span>Evidence before interpretation.</span><span>Research information, not legal advice. Built with Perplexity Computer.</span></footer>
    </div>
    {report&&<dialog open className="modal" aria-modal="true" aria-labelledby="correction-title"><div className="modal-head"><h2 id="correction-title">Propose a correction</h2><button className="icon-button" autoFocus aria-label="Close correction proposal" onClick={()=>setReport(null)} data-testid="button-close-correction"><X size={20}/></button></div><p>{report.label} · {report.title}</p><p className="muted">This creates a draft, not a submission. Nothing is sent, published or applied automatically.</p><form onSubmit={e=>{e.preventDefault();if(reason.trim().length<10){setReportError('Describe the correction in at least 10 characters.');return}try{const u=new URL(evidence);if(u.protocol!=='https:')throw Error()}catch{setReportError('Add a valid HTTPS evidence URL.');return}download(`correction-${report.id}.md`,correctionDraft(report,reason,evidence));setReportError('');setNotice('Correction proposal downloaded. Review it before sharing.');setReport(null)}}>
      <label htmlFor="correction-reason">What should change?</label><textarea id="correction-reason" data-testid="input-correction-reason" required maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/><label htmlFor="correction-evidence">Supporting evidence URL</label><input id="correction-evidence" data-testid="input-correction-evidence" type="url" required value={evidence} onChange={e=>setEvidence(e.target.value)}/>{reportError&&<p className="error" role="alert">{reportError}</p>}<button className="btn primary" data-testid="button-download-correction"><Download size={16}/>Download proposal</button></form><OutLink href={`${REPO}/issues/new`} testid="link-correction-issue">Open GitHub to submit after review</OutLink></dialog>}
    {report&&<div className="scrim" onClick={()=>setReport(null)}/>}
  </div>;
}
function Contributions(){
  const [family,setFamily]=useState('All');
  const shown=contributions.filter(p=>family==='All'||p.familyId===family);
  return <div className="page"><PageHead kicker="THIRTY REUSABLE RESEARCH OUTPUTS" title="The contribution index" description="Eighteen new briefs join the original twelve. Rules, prior-law context and recommendation lineage are kept distinct. These are documented outputs, not claims of exclusive discovery."/>
    <div className="collection-tools"><FamilySelect value={family} onChange={setFamily} testid="select-contribution-family"/><p data-testid="text-contribution-count">{shown.length} briefs shown · 30 total</p><a className="btn primary" href="./briefs/all-contributions.md" download data-testid="download-all-contributions"><Download size={16}/>Download all 30</a>{family!=='All'&&<a className="btn" href={`./briefs/${family}-contributions.md`} download data-testid="download-family-contributions">This collection<Download size={16}/></a>}</div>
    <section className="contribution-grid">{shown.map(p=><article className="contribution-card" key={p.id}><div className="finding-meta"><span>{families.find(f=>f.id===p.familyId)?.shortTitle}</span><Badge>{p.label}</Badge></div><h2>{p.title}</h2><p>{p.interpretation}</p><small className="muted">{p.comparisonKind}</small><div className="actions"><Link href={`/compare/${p.id}`} data-testid={`inspect-contribution-${p.id}`}>Inspect evidence<ArrowUpRight size={16}/></Link><a href={`./briefs/${p.id}.md`} download data-testid={`download-contribution-${p.id}`}>Download brief<Download size={16}/></a></div></article>)}</section>
    <div className="bottom-note"><CircleHelp size={20}/><div><h3>Contribution is not the same as novelty.</h3><p>These findings support enquiries, not claims that deployments, harms, legal compliance or institutional implementation have been proven. Their usefulness still needs testing in real work.</p></div></div></div>
}
function PageHead({kicker,title,description,children}:{kicker:string,title:string,description:string,children?:React.ReactNode}){return <div className="page-head"><div><p className="eyebrow">{kicker}</p><h1>{title}</h1><p className="lede">{description}</p></div>{children}</div>}
function Desk({notebook,toggle}:{notebook:Notebook,toggle:(id:string)=>void}){
  const featured=['sgi-definition','sgi-takedown','aig-incidents','aig-principles','rule-8','rule-14'].map(id=>data.provisions.find(p=>p.id===id)!);
  return <div className="page desk">
    <PageHead kicker="A RESEARCH DESK FOR DIGITAL POLICY" title="Policy changes, made inspectable." description="Follow the wording. Understand the limits. Take the evidence into your next story or decision."><Link className="btn primary" href="/compare/rule-8" data-testid="button-start-comparison">Open the comparison<ArrowRight size={16}/></Link></PageHead>
    <section className="collection-cards" aria-label="Policy collections">{families.map(f=><article className={`collection-card ${f.id}`} key={f.id}><div className="finding-meta"><span>{f.id==='dpdp'?'ORIGINAL COLLECTION':'NEW COLLECTION'}</span><Badge>{f.status}</Badge></div><h2>{f.shortTitle}</h2><p>{f.description}</p><details><summary data-testid={`timeline-${f.id}`}>Document lineage & coverage</summary><div className="lineage-mini">{f.timeline.map(t=><div key={t.date}><span className="dot"/><p><b>{t.date}</b>{t.title}<small>{t.detail}</small></p></div>)}</div><p className="tiny">{f.coverage}</p><p className="tiny">{f.scope}</p></details><Link href={`/compare/${f.defaultId}`} className="text-link" data-testid={`open-collection-${f.id}`}>Explore {f.count} comparisons<ArrowUpRight size={16}/></Link></article>)}</section>
    <div className="coverage-strip"><div><strong>56</strong><p>Comparison units</p></div><div><strong>13</strong><p>Official source records</p></div><div><strong>30</strong><p>Reusable research briefs</p></div><div className="coverage-note"><ShieldCheck size={20}/><p>Three bounded collections<br/><span>Not a live feed or legal audit</span></p></div></div>
    <div className="section-top"><div><p className="eyebrow">READ THE CHANGE, NOT JUST THE HEADLINE</p><h2>Start with consequential questions</h2></div><Link href="/compare/sgi-definition" className="text-link" data-testid="link-all-provisions">Browse comparisons<ArrowRight size={16}/></Link></div>
    <section className="finding-list" aria-label="Featured changes">{featured.map((p,i)=><article key={p.id} className="finding-row"><span className="row-number">0{i+1}</span><div><div className="finding-meta">{p.label}<Badge kind={p.type==='Addition'?'addition':''}>{p.type}</Badge></div><Link href={`/compare/${p.id}`} data-testid={`link-finding-${p.id}`}><h3>{p.title}<ArrowUpRight size={18}/></h3></Link><p>{p.summary}</p></div><button className={`icon-button save ${notebook.selected.includes(p.id)?'selected':''}`} aria-label={`${notebook.selected.includes(p.id)?'Remove':'Add'} ${p.label} ${notebook.selected.includes(p.id)?'from':'to'} brief`} title="Add or remove from brief" data-testid={`button-select-${p.id}`} onClick={()=>toggle(p.id)}>{notebook.selected.includes(p.id)?<Check size={18}/>:<Plus size={18}/>}</button></article>)}</section>
    <section className="bottom-note"><CircleHelp size={20}/><div><h3>Publication, legal effect and implementation are different.</h3><p>DPDP timing is qualified; SGI has an express commencement clause; AI governance recommendations are not automatically enacted mandates. Verify the relevant source and status before drawing a conclusion.</p></div><Link href="/method" className="text-link" data-testid="link-date-limits">Understand the limits<ArrowUpRight size={16}/></Link></section>
  </div>
}
function Compare({id,notebook,toggle,saveReview,report}:{id:string,notebook:Notebook,toggle:(id:string)=>void,saveReview:(r:Review)=>void,report:(p:Provision)=>void}){
  const [,navigate]=useHashLocation();
  const [family,setFamily]=useState(()=>data.provisions.find(p=>p.id===id)?.familyId||'All');
  const [query,setQuery]=useState(''),[type,setType]=useState('All'),[actor,setActor]=useState('All');
  const [corrected,setCorrected]=useState(true),[full,setFull]=useState(false),[highlight,setHighlight]=useState(true);
  const [reviewer,setReviewer]=useState(''),[note,setNote]=useState(''),[reviewStatus,setReviewStatus]=useState<'checked'|'disputed'>('checked');
  const [reviewError,setReviewError]=useState('');
  useEffect(()=>{setFull(false);setNote('');setReviewError('');const nextFamily=data.provisions.find(p=>p.id===id)?.familyId;setFamily(current=>current==='All'||!nextFamily?current:nextFamily)},[id]);
  const p=data.provisions.find(p=>p.id===id);
  const filtered=useMemo(()=>filterProvisions(data.provisions,query,type,actor,family) as Provision[],[query,type,actor,family]);
  if(!p)return <div className="page"><h1>Provision not found</h1><p>Choose a provision from the complete collection. No missing record has been generated.</p><Link href="/compare/rule-8" className="btn primary">Open complete comparison</Link></div>;
  const before=full?p.draftText:p.beforeExcerpt;
  let after=full?(corrected?p.correctedText:p.finalText):p.afterExcerpt;
  if(corrected&&!full&&p.id==='rule-1')after=after.replaceAll('of this Gazette','in the Official Gazette');
  if(corrected&&!full&&p.id==='rule-23')after=after.replace('given in such.','given in such order.');
  if(corrected&&p.familyId==='sgi'&&p.correctionIds.length&&!full)after=after.replaceAll('the Bharatiya Nagarik Suraksha Sanhita, 2023 (46 of 2023)','the Bharatiya Nyaya Sanhita, 2023 (45 of 2023) read with the Bharatiya Nagarik Suraksha Sanhita, 2023 (46 of 2023)');
  const doHighlight=highlight&&!p.id.startsWith('schedule')&&p.familyId!=='aig';
  const chunks=doHighlight?diffWordsWithSpace(before,after):null;
  const links=evidenceLinks(p);
  const selectedFamily=families.find(f=>f.id===p.familyId)!;
  const review=notebook.reviews.filter(r=>r.provisionId===p.id);
  return <div className="compare-page">
    <div className="comparison-top"><div><p className="eyebrow">{selectedFamily.shortTitle} · {p.comparisonKind}</p><h1>Compare provisions</h1></div><button className={`btn ${notebook.selected.includes(id)?'selected':'primary'}`} onClick={()=>toggle(id)} data-testid="button-add-to-brief">{notebook.selected.includes(id)?<Check size={16}/>:<Plus size={16}/>} {notebook.selected.includes(id)?'In your brief':'Add to brief'}</button></div>
    <div className="collection-tools compare-families"><FamilySelect value={family} onChange={value=>{setFamily(value);setQuery('');setType('All');setActor('All');if(value!=='All')navigate(`/compare/${families.find(f=>f.id===value)!.defaultId}`)}} testid="select-comparison-family"/><div><b>{selectedFamily.shortTitle}</b><p className="tiny" data-testid="text-comparison-kind">{p.comparisonKind} · {p.legalStatus||'Notified rules; timing limits apply'}</p></div></div>
    <div className="compare-grid">
      <aside className="provision-nav"><label className="search-box"><Search size={16}/><span className="sr-only">Search provisions</span><input data-testid="input-search" placeholder="Search provisions…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="sr-only" htmlFor="type-filter">Change type</label><select id="type-filter" data-testid="select-type" value={type} onChange={e=>setType(e.target.value)}>{['All','Addition','Scope change','Qualification','Wording','Timing','Continuity'].map(t=><option key={t} value={t}>{t==='All'?'All change types':t}</option>)}</select><label className="sr-only" htmlFor="actor-filter">Actor or class</label><select id="actor-filter" data-testid="select-actor" value={actor} onChange={e=>setActor(e.target.value)}><option value="All">All actors / classes</option>{[...new Set(data.provisions.map(p=>p.actor))].map(a=><option key={a}>{a}</option>)}</select><div className="list-count" data-testid="text-filter-count">{filtered.length} shown · {family==='All'?56:families.find(f=>f.id===family)?.count} in scope<button data-testid="button-reset-filters" onClick={()=>{setQuery('');setType('All');setActor('All')}}>Reset</button></div><nav aria-label="Provision navigation">{filtered.map(r=><Link key={r.id} href={`/compare/${r.id}`} className={`provision-link ${r.id===id?'active':''}`} data-testid={`link-provision-${r.id}`}><span>{r.label}<small>{r.type}</small></span><b>{r.title}</b></Link>)}</nav>{filtered.length===0&&<div className="empty compact"><Search size={24}/><h3>No matching provisions</h3><p>Try broader words or clear your filters. The selected comparison remains open.</p></div>}</aside>
      <article className="comparison">
        {id==='rule-8'&&<div className="correction-inline" data-testid="text-alignment-note"><CircleHelp size={16}/><span>Alignment note: draft sub-rule (3) defined “user account”; that definition moved to final Rule 2. Final sub-rule (3) adds retention duties. Highlighting these excerpts does not mean the definition was abolished.</span><Link href="/compare/rule-2">Inspect relocation</Link></div>}
        <div className="record-header"><div className="record-kicker">{p.label} <Badge kind={p.type==='Addition'?'addition':''}>{p.type}</Badge></div><h2>{p.title}</h2><div className="record-meta"><span>{p.actor}</span><span>{p.familyId==='dpdp'?'Draft':'Earlier source'}: {p.draftLabel}</span></div><p className="summary">{p.summary}</p></div>
        <div className="evidence-toolbar">{p.familyId==='aig'?<Badge>As published · no directed correction recorded</Badge>:<div className="segmented" aria-label="Later text version"><button aria-pressed={!corrected} data-testid="button-as-printed" onClick={()=>setCorrected(false)}>As printed</button><button aria-pressed={corrected} data-testid="button-as-corrected" onClick={()=>setCorrected(true)}>As corrected</button></div>}<label className="check"><input type="checkbox" data-testid="input-highlight" disabled={p.familyId==='aig'} checked={p.familyId==='aig'?false:highlight} onChange={e=>setHighlight(e.target.checked)}/>{p.familyId==='aig'?'No automatic lineage diff':'Word changes'}</label></div>
        {p.correctionIds.length>0&&<div className="correction-inline"><ListChecks size={16}/><span>{corrected?'Official corrections applied to the full text':'Original final print; later corrections not applied'} · {p.correctionIds.join(', ')}</span><Link href="/corrections" data-testid="link-record-corrections">Inspect</Link></div>}
        <section className="evidence-grid" aria-label="Source wording"><div className="text-panel old"><header><span>{p.beforeLabel||'CONSULTATION DRAFT'}</span><OutLink href={links.before} testid="link-draft-page">{p.draftLocator?'Open source':`p. ${p.draftPage}`}</OutLink></header><div className="quoted" data-testid="text-draft-evidence">{chunks?chunks.filter(c=>!c.added).map((c,i)=><span key={i} className={c.removed?'removed':''}>{c.value}</span>):before}</div><p className="evidence-locator">{links.beforeLocator}</p></div><div className="text-panel new"><header><span>{p.afterLabel||'FINAL'} · {p.familyId==='aig'?'AS PUBLISHED':corrected?'CORRECTED':'AS PRINTED'}</span><OutLink href={links.after} testid="link-final-page">{p.finalLocator?'Open source':`p. ${p.finalPage}`}</OutLink></header><div className="quoted" data-testid="text-final-evidence">{chunks?chunks.filter(c=>!c.removed).map((c,i)=><span key={i} className={c.added?'added':''}>{c.value}</span>):after}</div><p className="evidence-locator">{links.afterLocator}</p></div></section>
        <div className="evidence-bottom"><button className="text-link" data-testid="button-full-text" onClick={()=>setFull(!full)}>{full?'Show focused excerpts':p.familyId==='dpdp'?'Read full provision text':'Read mapped evidence segments'}<ChevronDown size={16} className={full?'rotated':''}/></button><span>{p.familyId==='aig'?'Thematic lineage, not a word-aligned legal redline.':p.id.startsWith('schedule')?'Table text is extracted; no automatic table diff.':'Word highlighting is mechanical, not legal classification.'}</span></div>
        {p.evidenceScope&&<p className="tiny muted">{p.evidenceScope}</p>}
        <section className="analysis-grid"><div><p className="eyebrow">ANALYST INTERPRETATION</p><h3>What this may mean</h3><p>{p.interpretation}</p><p className="eyebrow space-top">REPORTING QUESTION</p><p>{p.question}</p></div><div className="limits"><CircleHelp size={18}/><h3>Before drawing a conclusion</h3><p>{p.caution}</p><OutLink href={p.familyId==='dpdp'?ACT_URL:links.after} testid="link-parent-act">{p.familyId==='dpdp'?'Read the parent Act':'Read the complete later source'}</OutLink><p className="tiny">Review: {p.reviewStatus}. Evidence checked {p.familyId==='dpdp'?'4':'5'} October 2026.</p></div></section>
        <section className="review-section"><div className="section-top"><div><p className="eyebrow">PRIVATE, IN THIS SESSION</p><h3>Your review notes</h3></div><button className="text-link" data-testid="button-propose-correction" onClick={()=>report(p)}>Propose a correction<ArrowUpRight size={16}/></button></div><p className="muted">Notes are not published or permanently stored. Export the notebook to keep them; import it to resume.</p><form onSubmit={e=>{e.preventDefault();if(!reviewer.trim()||note.trim().length<5){setReviewError('Add a reviewer name and a note of at least 5 characters.');return}saveReview({provisionId:id,reviewer:reviewer.trim(),note:note.trim(),status:reviewStatus,timestamp:new Date().toISOString()});setNote('');setReviewError('')}}><div className="form-row"><label>Reviewer<input data-testid="input-reviewer" value={reviewer} maxLength={100} required onChange={e=>setReviewer(e.target.value)} placeholder="Your name or role"/></label><label>Session status<select data-testid="select-review-status" value={reviewStatus} onChange={e=>setReviewStatus(e.target.value as 'checked'|'disputed')}><option value="checked">Checked with a note</option><option value="disputed">Needs further verification</option></select></label></div><label>Evidence note<textarea data-testid="input-review-note" value={note} maxLength={4000} required onChange={e=>setNote(e.target.value)} placeholder="What did you check? What remains uncertain?"/></label>{reviewError&&<p className="error" role="alert">{reviewError}</p>}<button className="btn" data-testid="button-save-review"><Check size={16}/>Save session review</button></form>{review.map((r,i)=><div className="review-event" key={i} data-testid={`review-event-${i}`}><b>{r.reviewer}</b><Badge>{r.status}</Badge><p>{r.note}</p><small>{new Date(r.timestamp).toLocaleString()}</small></div>)}</section>
      </article>
    </div>
  </div>
}
function Sources(){
  const [family,setFamily]=useState('All');
  const shown=data.sources.filter(s=>family==='All'||sourceFamily(s.id)===family);
  return <div className="page"><PageHead kicker="THREE COLLECTIONS · THIRTEEN OFFICIAL SOURCE RECORDS" title="The source library" description="Consultation drafts, consolidated law, notified amendments, policy recommendations and explanations are not interchangeable. Inspect status and lineage before interpretation."/>
  <div className="collection-tools"><FamilySelect value={family} onChange={setFamily} testid="select-source-family"/><p data-testid="text-source-count">{shown.length} sources shown</p><a href="./combined-data.json" download className="btn" data-testid="download-combined-data">Complete structured collection<Download size={16}/></a></div>
  {(family==='All'||family==='dpdp')&&<div className="warning"><CircleHelp size={18}/><p><b>DPDP publication-date basis is unresolved here.</b> The final instrument is dated 13 November; MeitY lists publication on 14 November. Calculated commencement dates are not certified deadlines.</p></div>}
  <section className="source-list">{shown.map((s,i)=><article className="source-card" key={s.id}><div className="source-index">{String(i+1).padStart(2,'0')}</div><div><div className="finding-meta">{s.instrument}<Badge>{s.status}</Badge></div><h2>{s.title}</h2><p>{s.description}</p><dl><div><dt>Document date</dt><dd>{s.documentDate}</dd></div><div><dt>Publication record</dt><dd>{s.publication}</dd></div><div><dt>Source check</dt><dd>{s.checked}</dd></div></dl><div className="source-actions"><OutLink href={s.url} testid={`link-source-${s.id}`}>Open official source</OutLink><a href={`./${s.snapshot}`} download data-testid={`download-snapshot-${s.id}`}><Download size={15}/>Extracted text snapshot</a></div><details><summary data-testid={`details-integrity-${s.id}`}>Inspect snapshot integrity</summary><p className="tiny">{s.hashType}. These snapshots are not PDF binaries and are not a bilingual legal audit.</p><code className="hash">{s.hash}</code></details></div></article>)}</section>
  <section className="bottom-note"><FileText size={20}/><div><h3>Research packages and statutory context</h3><p>The original DPDP study and expansion study document different collections. The DPDP parent Act is relevant to that collection, not a parent statute for every recommendation here.</p></div><div className="stack-links"><OutLink href={ACT_URL} testid="link-source-act">DPDP parent Act</OutLink><a href="./research/study.md" download data-testid="download-study">Original DPDP study<Download size={15}/></a><a href="./research/expansion-study.md" download data-testid="download-source-expansion-study">Expansion study<Download size={15}/></a><a href="./combined-data.json" download data-testid="download-dataset">Structured collection<Download size={15}/></a></div></section>
  </div>}
function Corrections(){
  const [family,setFamily]=useState('All');
  const shown=data.corrections.filter(c=>family==='All'||c.familyId===family);
  return <div className="page"><PageHead kicker="TEN DIRECTED ENGLISH SUBSTITUTIONS" title="The correction register" description="Eight DPDP substitutions and two synthetic-media citation corrections. Each belongs to a specific source and locator, not a global find-and-replace."/><div className="collection-tools"><FamilySelect value={family} onChange={setFamily} testid="select-correction-family"/><p>{shown.length} directed English corrections shown</p></div><div className="corrections-table">{shown.map(c=><article className="correction-row" key={c.id}><div><span className="mono">{c.id}</span><small>{c.locator}</small></div><div><span className="eyebrow">AS PRINTED</span><p className="correction-quote removed">{c.before}</p></div><div><span className="eyebrow">DIRECTED REPLACEMENT</span><p className="correction-quote added">{c.after}</p><p className="tiny">{c.note}</p><OutLink href={c.sourceUrl!} testid={`link-correction-source-${c.id}`}>Official correction</OutLink></div><Link href={`/compare/${c.provisionId}`} className="icon-button" aria-label={`Inspect ${c.id} provision`} data-testid={`link-correction-${c.id}`}><ArrowUpRight size={20}/></Link></article>)}</div>{shown.length===0&&<div className="empty" data-testid="text-no-corrections"><h2>No directed English corrections in this collection.</h2><p>This is the register's verified scope, not proof that no later correction exists.</p></div>}<div className="bottom-note"><ShieldCheck size={20}/><div><h3>A correction is part of the evidence chain.</h3><p>The comparison preserves the final as printed and applies only the directed English corrections. Hindi-only changes are not conflated with this register. Other apparent typos are not silently repaired.</p></div></div></div>
}
function Brief({notebook,setNotebook,notify}:{notebook:Notebook,setNotebook:React.Dispatch<React.SetStateAction<Notebook>>,notify:(s:string)=>void}){
  const selected=notebook.selected.map(id=>data.provisions.find(p=>p.id===id)!);
  const [preview,setPreview]=useState(false),[error,setError]=useState('');
  const text=createBrief(data,notebook);
  function move(index:number,delta:number){setNotebook(n=>{const s=[...n.selected];[s[index],s[index+delta]]=[s[index+delta],s[index]];return {...n,selected:s}})}
  return <div className="page"><PageHead kicker="TURN EVIDENCE INTO A WORKING BRIEF" title="Your brief" description="Select provisions, keep the caveats, and export the evidence. Everything here stays in this browser session until you download it."/>
    <div className="brief-tools"><label className="import btn"><Upload size={16}/>Import notebook<input data-testid="input-import-notebook" type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>2000000)throw Error('Notebook exceeds the 2 MB limit.');const value=validateNotebook(JSON.parse(await f.text()),data.provisions.map(p=>p.id));setNotebook(value as Notebook);setError('');notify('Notebook imported locally. Nothing was uploaded.')}catch(err){setError(err instanceof Error?err.message:'Unable to read notebook.')}e.target.value=''}}/></label><button className="btn" data-testid="button-export-notebook" onClick={()=>{download('ai-watch-notebook.json',JSON.stringify(notebook,null,2),'application/json');notify('Notebook exported. Keep it to restore your selection and review notes.')}}><Download size={16}/>Save notebook</button><button className="text-link" data-testid="button-clear-notebook" onClick={()=>{setNotebook({version:1,title:'Digital policy change brief',selected:[],reviews:[]});setPreview(false);notify('Session notebook cleared. Previously downloaded files are unchanged.')}}>Clear session</button></div>
    {error&&<p className="error" role="alert" data-testid="status-import-error">{error} Your existing notebook was not changed.</p>}
    <label className="brief-title">Brief title<input data-testid="input-brief-title" maxLength={200} value={notebook.title} onChange={e=>setNotebook(n=>({...n,title:e.target.value}))}/></label>
    {selected.length===0?<section className="empty"><NotebookPen size={32}/><h2>Begin with one meaningful change.</h2><p>Add a provision from the comparison. Your brief will keep the original sources, interpretation and uncertainty together.</p><Link href="/compare/rule-8" className="btn primary" data-testid="button-empty-compare">Explore provisions<ArrowRight size={16}/></Link></section>:<section className="brief-list">{selected.map((p,i)=><article className="brief-row" key={p.id}><span className="row-number">{String(i+1).padStart(2,'0')}</span><div><Badge>{p.label}</Badge><Link href={`/compare/${p.id}`} data-testid={`link-brief-${p.id}`}><h3>{p.title}</h3></Link><p>{p.summary}</p><small>{notebook.reviews.filter(r=>r.provisionId===p.id).length} local review notes · Sources and caveats included</small></div><div className="reorder"><button className="icon-button" disabled={i===0} aria-label={`Move ${p.label} up`} onClick={()=>move(i,-1)} data-testid={`button-up-${p.id}`}><MoveUp size={16}/></button><button className="icon-button" disabled={i===selected.length-1} aria-label={`Move ${p.label} down`} onClick={()=>move(i,1)} data-testid={`button-down-${p.id}`}><MoveDown size={16}/></button><button className="icon-button" aria-label={`Remove ${p.label}`} data-testid={`button-remove-${p.id}`} onClick={()=>setNotebook(n=>({...n,selected:n.selected.filter(id=>id!==p.id)}))}><X size={16}/></button></div></article>)}</section>}
    <div className="export-bar"><div><b data-testid="text-selected-count">{selected.length} selected provisions</b><p>Working research, not a legal opinion.</p></div><div><button className="btn" disabled={!selected.length} data-testid="button-preview-brief" onClick={()=>setPreview(!preview)}>{preview?'Hide':'Preview'} brief</button><button className="btn" disabled={!selected.length} data-testid="button-export-csv" onClick={()=>download('policy-change-brief.csv',csv(selected),'text/csv;charset=utf-8')}>CSV</button><button className="btn primary" disabled={!selected.length} data-testid="button-export-markdown" onClick={()=>{download('policy-change-brief.md',text);notify('Source-linked Markdown brief downloaded.')}}><Download size={16}/>Export Markdown</button></div></div>
    {preview&&selected.length>0&&<section className="preview"><h2>Export preview</h2><p className="muted">Exact Markdown output. Select and copy the text if downloads are restricted by your browser.</p><textarea aria-label="Markdown brief preview" data-testid="text-brief-preview" readOnly value={text}/></section>}
    <div className="bottom-note"><ShieldCheck size={20}/><div><h3>Private by design for this release.</h3><p>No account, external model calls, analytics or server uploads. Notebook imports are processed locally. A reload clears session notes unless you export and import them.</p></div></div>
  </div>
}
function Method(){return <div className="page method"><PageHead kicker="WHAT CAN BE VERIFIED, AND WHAT CANNOT" title="Method & limits" description="Confidence comes from a visible evidence chain, not a fluent summary. This is a bounded collection, with its limits kept alongside its findings."/>
  <section><h2>Scope and coverage</h2>{families.map(f=><div key={f.id} className="method-family"><h3>{f.shortTitle}</h3><p>{f.coverage}</p><p>{f.scope}</p><Link href={`/compare/${f.defaultId}`} className="text-link">Inspect this collection<ArrowUpRight size={16}/></Link></div>)}<p>Three bounded collections, 56 comparison units and 30 briefs. SGI changes absent from the consultation use clearly labelled prior-law context. AI guidelines are thematic recommendation lineage, not a one-to-one legal redline. All sources are extracted text, not a certified bilingual audit.</p></section>
  <section><h2>Rules are not recommendations</h2><p>Notified rules, consolidated law, policy recommendations and official explanations are labelled separately. A recommendation to set up a body, database or obligation is not proof it was implemented. AI-guidelines printed-page locators are not asserted to be PDF-page indices.</p><p>AI recommendation lineage and flattened action-plan tables are not mechanically diff-highlighted. This prevents prose restructuring from being misread as a legal deletion. The SGI register tracks two English substitutions; four Hindi-language substitutions are outside this English comparison.</p><a className="text-link" href="./research/expansion-study.md" download data-testid="download-expansion-study">Read the expansion study<Download size={16}/></a></section>
  <section><h2>Three layers, never collapsed</h2><dl className="method-layers"><div><dt>01 · Evidence</dt><dd>Original wording, official URL, provision identity, print-page locator and extracted-text integrity.</dd></div><div><dt>02 · Interpretation</dt><dd>Analyst explanation of potential significance. Single-analyst review, not independent legal approval.</dd></div><div><dt>03 · Follow-up</dt><dd>Reporting questions and unresolved dependencies. No interviews, enquiries or corrections have been sent automatically.</dd></div></dl></section>
  <section><h2>Timing without false certainty</h2><p>Rule 1 specifies publication for rules 1, 2 and 17–21; one year after publication for rule 4; and eighteen months for rules 3, 5–16, 22 and 23. The corrigendum changes the delayed-commencement wording to “in the Official Gazette.”</p><div className="inline-sources"><OutLink href={FINAL_URL}>Rule 1</OutLink><OutLink href={CORRECTION_URL}>Correction to Rule 1</OutLink></div><p>Published explanations use competing 13/14 November bases. This release records the formula and flags the dispute; it does not provide a definitive compliance countdown.</p><div className="inline-sources"><OutLink href="https://www.meity.gov.in/documents/act-and-policies/digital-personal-data-protection-rules-2025-gDOxUjMtQWa">MeitY metadata</OutLink><OutLink href="https://www.pib.gov.in/PressReleasePage.aspx?PRID=2190655&reg=3&lang=2">PIB explanation</OutLink></div></section>
  <section><h2>Extraction and correction discipline</h2><p>Raw extracted snapshots are preserved. Layout normalization creates a derived text layer; tables are not automatically scored because reading-order artifacts can look like legal changes. Mechanical word highlights are aids, not legal conclusions.</p><p>Official substitutions are applied to specific provision targets. Original print remains inspectable, and unrelated apparent typographical errors are not silently corrected.</p></section>
  <section><h2>Known gaps</h2><ul><li>No complete current court-order chain or exhaustive later-amendment search is certified.</li><li>No interviews, adoption tests or willingness-to-pay findings are claimed.</li><li>Snapshots are extracted text; original PDF binaries are linked, not archived here.</li><li>Local review notes are private session annotations, not authenticated public approvals.</li><li>The collection is curated, not a live national policy monitor.</li></ul></section>
  <section><h2>How to challenge a finding</h2><p>Open a provision and choose “Propose a correction.” Add the proposed correction and an HTTPS evidence URL, download the draft, then submit it manually through the repository if appropriate. Public records change only through a reviewed source update.</p><OutLink href={`${REPO}/issues`} testid="link-method-issues">Repository correction queue</OutLink></section>
  <section><h2>Reusable research</h2><p>The data, source snapshots, editorial observations and application source are available to inspect and improve. A useful contribution must still be established through real reporting and policy tasks, not assumed from the interface.</p><div className="inline-sources"><a href="./research/study.md" download data-testid="download-method-study">Full study<Download size={15}/></a><a href="./research/specification.md" download data-testid="download-method-spec">Product specification<Download size={15}/></a><a href="./combined-data.json" download data-testid="download-method-data">Structured data<Download size={15}/></a><OutLink href={REPO}>Application source</OutLink></div></section>
  </div>}
createRoot(document.getElementById('root')!).render(<Router hook={useHashLocation}><App/></Router>);
