import { useEffect,useMemo,useState } from 'react';
import { Link } from 'wouter';
import { ArrowRight,Download,Search,ExternalLink,FileText } from 'lucide-react';
import {filterSystems,registryCsv,recordEvidence} from './registry-lib.mjs';
import {GovernanceLinks} from './Governance';
import {DeploymentEvidenceLinks} from './DeploymentEvidence';
type Row=Record<string,any>;
type Data={metadata:Row;systems:Row[];institutions:Row[];assertions:Row[];evidence:Row[];evidence_links:Row[];sources:Row[];[key:string]:any};
function save(name:string,text:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function DownloadFile({file,children}:{file:string,children:React.ReactNode}){return <a className="btn" href={`./registry/${file}`} download data-testid={`registry-download-${file.replaceAll('/','-')}`}><Download size={15}/>{children}</a>}
function Evidence({data,table,id}:{data:Data,table:string,id:string}){
 const rows=recordEvidence(data,table,id) as Row[];
 return <div className="registry-evidence">{rows.map(e=><details key={e.evidence_id}>
  <summary>Inspect evidence · {e.source?.title}</summary><blockquote>{e.quote}</blockquote>
  <p className="fine">{e.locator}<br/>{e.source?.source_type} · {e.source?.published_date||'Undated/uncertain'}<br/>{e.source?.date_basis}<br/>Source recheck: {data.source_rechecks?.find((r:Row)=>r.source_id===e.source_id)?.status||'New source: selected excerpts checked against fetched text; not independent review'}</p>
  {e.source?.retrieval_basis&&<p className="fine">Retrieval: {e.source.retrieval_basis}. Cached extraction: {String(e.source.is_cached)}.</p>}
  <a className="text-link" href={e.source?.url} target="_blank" rel="noreferrer">Read original record <ExternalLink size={13}/></a> <a className="text-link" href={`./registry/${e.source?.snapshot}`} download>Selected snapshot</a>
 </details>)}</div>
}
export default function Registry({mode='explore',id}:{mode?:'explore'|'data'|'system',id?:string}){
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
  useEffect(()=>{let active=true;setError('');fetch('./registry/data.json').then(r=>{if(!r.ok)throw Error('Unavailable');return r.json()}).then(d=>{if(!d.metadata||!Array.isArray(d.systems))throw Error('Invalid');if(active)setData(d)}).catch(()=>{if(active)setError('The dataset could not be loaded. Retry or retrieve it from the repository.')});return()=>{active=false}},[retry]);
  if(error)return <div className="page"><h1>Dataset unavailable</h1><p role="alert">{error}</p><button className="btn" onClick={()=>setRetry(retry+1)}>Retry dataset</button><a className="btn" href="https://github.com/nawaaaaaAaar/ai-watch-india/tree/main/public/registry" target="_blank" rel="noreferrer">Repository data</a></div>;
  if(!data)return <div className="page" role="status"><h1>Loading the evidence dataset</h1><p>Preparing linked systems, institutions and source records.</p></div>;
  return mode==='data'?<DataRoom data={data}/>:mode==='system'?<System data={data} id={id||''}/>:<Explorer data={data}/>;
}
function Explorer({data}:{data:Data}){
  const [query,setQuery]=useState(''),[sector,setSector]=useState('All'),[stage,setStage]=useState('All'),[ai,setAi]=useState('All'),[frame,setFrame]=useState('All'),[cohort,setCohort]=useState('All'),[sort,setSort]=useState('name');
  const rows=useMemo(()=>filterSystems(data,{query,sector,stage,ai,frame,cohort,sort}) as Row[],[data,query,sector,stage,ai,frame,cohort,sort]);
  const reset=()=>{setQuery('');setSector('All');setStage('All');setAi('All');setFrame('All');setCohort('All');setSort('name')};
  return <div className="page registry">
    <header className="page-head"><div><p className="eyebrow">INDIA · RESEARCH DATASET · V{data.metadata.version}</p><h1>Who is using AI.<br/>What can we verify?</h1><p className="lede">Follow a named system to the institution, deployment evidence and unanswered questions behind it. Source-linked data for governance research and reporting, not a leaderboard.</p></div><Link className="btn primary" href="/registry-data">Use the dataset <ArrowRight size={16}/></Link></header>
    <div className="registry-scope"><b>Source-linked research, not a national census.</b><p>{data.systems.length} named system/service families across four research cohorts, not {data.systems.length} independently verified live AI deployments. Proposed, historical, internal, enabling and qualified algorithmic contexts are distinguished. “Documented” supports a source statement, not an operational audit.</p><Link className="text-link" href="/registry-data">Inspect coverage, research rounds and source review <ArrowRight size={14}/></Link></div>
    <section className="registry-leads" aria-label="Research leads">
      <Link href="/system/sys-epaarvai"><span className="eyebrow">EVALUATION</span><h2>Accuracy is not the whole result</h2><p>Inspect the cataract study’s specificity, sample and setting alongside accuracy.</p><span className="text-link">Open e-Paarvai evidence <ArrowRight size={14}/></span></Link>
      <Link href="/system/sys-rail-ids"><span className="eyebrow">CLAIM TYPE</span><h2>A requirement is not a result</h2><p>Separate elephant-detection thresholds, working coverage and reported outcomes.</p><span className="text-link">Open railway evidence <ArrowRight size={14}/></span></Link>
      <Link href="/system/sys-bharat-vistaar"><span className="eyebrow">PUBLIC MONEY</span><h2>Allocated is not spent</h2><p>Keep a budget statement distinct from supplier awards and disbursements.</p><span className="text-link">Open funding evidence <ArrowRight size={14}/></span></Link>
    </section>
    <div className="registry-filter">
      <label className="registry-query"><Search size={16}/><span className="sr-only">Search systems and evidence</span><input placeholder="Search system, institution or evidence…" value={query} onChange={e=>setQuery(e.target.value)} data-testid="registry-search"/></label>
      {[['Sector',sector,setSector,'sector'],['Documentary stage',stage,setStage,'stage'],['AI attribution',ai,setAi,'ai_class']].map(([label,value,setter,key])=><label key={String(key)}>{String(label)}<select value={String(value)} onChange={e=>(setter as (v:string)=>void)(e.target.value)} data-testid={`registry-filter-${key}`}><option value="All">All</option>{[...new Set(data.systems.map(s=>String(s[String(key)])))].sort().map(v=><option key={v}>{v}</option>)}</select></label>)}
      <label>Original institutional frame<select value={frame} onChange={e=>setFrame(e.target.value)} data-testid="registry-filter-frame"><option value="All">All</option>{data.institution_coverage.map((f:Row)=><option key={f.frame_id} value={f.frame_id}>{f.institution_name}</option>)}<option value="Outside frame">Outside original fixed frame</option></select></label>
      <label>Research cohort<select value={cohort} onChange={e=>setCohort(e.target.value)} data-testid="registry-filter-cohort"><option value="All">All research rounds</option>{[...new Set(data.systems.map(s=>String(s.research_round)))].sort().map(v=><option key={v} value={v}>v{v}</option>)}</select></label>
      <label>Sort<select value={sort} onChange={e=>setSort(e.target.value)} data-testid="registry-sort"><option value="name">System name</option><option value="date">Latest dated record</option></select></label>
    </div>
    <div className="registry-result-bar"><p role="status" data-testid="registry-result-count">{rows.length} of {data.systems.length} selected systems · one row per service/system</p><button className="btn small" onClick={()=>save('ai-watch-filtered-systems.csv',registryCsv(data,rows))} data-testid="registry-export-filtered"><Download size={15}/>Export this view</button><button className="btn small" onClick={reset} data-testid="registry-reset">Reset filters</button></div>
    <p className="fine">“Latest dated record” is a source date, not the last successful operation. Explicit AI attribution includes vendor/editorial claims, not independent or government validation. Undated evidence is retained in each dossier.</p>
    <div className="registry-table-wrap"><table className="registry-table"><thead><tr><th>System / responsible institution</th><th>Public-service context</th><th>What the records establish</th><th>Dated evidence</th></tr></thead><tbody>{rows.map(s=><tr key={s.system_id} data-testid={`registry-row-${s.system_id}`}><td><Link href={`/system/${s.system_id}`} className="registry-name">{s.name}<ArrowRight size={14}/></Link><p>{data.institutions.find(i=>i.institution_id===s.owner_institution_id)?.name}</p></td><td>{s.sector}<p>{s.jurisdiction}</p></td><td><span className="registry-stage">{s.stage}</span><p>{s.ai_basis}</p></td><td>{s.latest_record_date||'Undated / mixed'}<p><a href={`./registry/dossiers/${s.system_id}.md`} download>Full dossier <FileText size={13}/></a></p></td></tr>)}</tbody></table>{!rows.length&&<div className="registry-empty"><h2>No matching systems in this seed</h2><p>This does not establish that no such system exists. Try a broader search or reset the filters.</p><button className="btn" onClick={reset}>Show all selected systems</button></div>}</div>
    <footer className="registry-footer"><p>The contribution is inspectable data and coding, not the number of pages. Read source context before comparing systems.</p><Link href="/desk" className="text-link">Open supporting policy evidence <ArrowRight size={14}/></Link></footer>
  </div>
}
function System({data,id}:{data:Data,id:string}){
  const s=data.systems.find(s=>s.system_id===id);
  if(!s)return <div className="page"><h1>System not in this release</h1><p>No dossier matches this identifier. The seed does not cover every Indian AI system.</p><Link className="btn" href="/">Return to systems</Link></div>;
  const assertions=data.assertions.filter(a=>a.system_id===id);
  const owner=data.institutions.find(i=>i.institution_id===s.owner_institution_id);
  return <div className="page registry registry-detail">
    <Link className="text-link" href="/">← Systems dataset</Link>
    <header className="page-head"><div><p className="eyebrow">{s.sector.toUpperCase()} · {s.jurisdiction}</p><h1>{s.name}</h1><p className="lede">{owner?.name}<br/>{s.stage}. {s.ai_basis}.</p></div><DownloadFile file={`dossiers/${id}.md`}>Download full dossier</DownloadFile></header>
    <div className="registry-scope"><b>Documentary evidence, not an operational audit.</b><p>Last coded dated record: {s.latest_record_date||'Undated / mixed'}. Checked {s.checked_date}. Historical requirements and self-reports do not certify current effectiveness. Institution names are source-stated, not registry-certified ownership.</p></div>
    <p className="fine">Record kind: {s.system_kind}. Selection: {s.selection}. Frame association is documentary coverage, not ownership or a representative sample.</p>
    <GovernanceLinks systemId={id}/>
    <DeploymentEvidenceLinks systemId={id}/>
    <h2>All twelve accountability dimensions</h2>
    <div className="registry-assertions">{assertions.map(a=><article key={a.assertion_id} data-testid={`assertion-${a.assertion_id}`}><div className="registry-assertion-head"><h3>{a.field}</h3><span className={`registry-status ${a.evidence_status==='Not verified'?'unknown':''}`}>{a.evidence_status}</span></div><p>{a.value}</p><Evidence data={data} table="assertions" id={a.assertion_id}/>{!data.evidence_links.some(l=>l.record_type==='assertions'&&l.record_id===a.assertion_id)&&<p className="fine">No supporting record established in this reviewed corpus. Not proof that none exists.</p>}</article>)}</div>
    {['deployments','procurements','evaluations','metrics','controls','issues'].map(table=>{
      const rows=(data[table] as Row[]).filter(r=>r.system_id===id);if(!rows.length)return null;
      return <section className="registry-observations" key={table}><h2>{({deployments:'Dated and undated deployment observations',procurements:'Funding and procurement records',evaluations:'Evaluation-related evidence',metrics:'Typed metrics · not comparable scores',controls:'Published safeguards and routes',issues:'Unresolved distinctions'})[table]}</h2>{rows.map(r=><article key={String(Object.values(r)[0])}><dl>{Object.entries(r).filter(([k])=>!['system_id',Object.keys(r)[0],'supplier_institution_id'].includes(k)).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{v==null?'Not established / not assigned':String(v)}</dd></div>)}</dl><Evidence data={data} table={table} id={String(Object.values(r)[0])}/></article>)}</section>
    })}
    <section className="registry-observations"><h2>Institution and system relationships</h2>{data.system_institutions.filter((r:Row)=>r.system_id===id).map((r:Row)=><article key={r.role_id}><h3>{data.institutions.find(i=>i.institution_id===r.institution_id)?.name}</h3><p>{r.role}</p><Evidence data={data} table="system_institutions" id={r.role_id}/></article>)}{data.system_links.filter((r:Row)=>r.system_id===id||r.target_system_id===id).map((r:Row)=><article key={r.system_link_id}><Link className="text-link" href={`/system/${r.system_id===id?r.target_system_id:r.system_id}`}>{data.systems.find(s=>s.system_id===(r.system_id===id?r.target_system_id:r.system_id))?.name}</Link><p>{r.relation}. {r.note}</p><Evidence data={data} table="system_links" id={r.system_link_id}/></article>)}</section>
    {data.system_policy_links.some((r:Row)=>r.system_id===id)&&<section className="registry-observations"><h2>Direct policy / terms links</h2>{data.system_policy_links.filter((r:Row)=>r.system_id===id).map((r:Row)=><article key={r.policy_link_id}><h3>{data.policies.find((p:Row)=>p.policy_id===r.policy_id)?.title}</h3><p>{r.relation}</p><Evidence data={data} table="system_policy_links" id={r.policy_link_id}/></article>)}</section>}
    <footer className="registry-footer"><Link className="btn" href="/registry-data">Methods, tables and reusable queries</Link>{s.legacy_id&&<Link className="btn" href={`/compare/${s.legacy_id}`}>Earlier case file and research brief</Link>}</footer>
  </div>;
}
function DataRoom({data}:{data:Data}){
  const tables=Object.keys(data.metadata.counts);
  return <div className="page registry"><header className="page-head"><div><p className="eyebrow">REUSABLE DATA · NOT A BLACK BOX</p><h1>The dataset comes first</h1><p className="lede">Download the linked records, inspect the coding and run your own queries. All twelve fields remain present for every system, including explicit unknowns.</p></div><DownloadFile file="complete-registry.zip">Complete research package</DownloadFile></header>
    <div className="registry-scope"><b>Scope and review status</b><p>{data.metadata.scope} {data.metadata.review}. No national prevalence, safety score, independent legal assurance or user-demand validation is claimed.</p><p>Systems and policy provisions have different units and are not pooled. Existing policy collections remain supporting evidence.</p></div>
    <section className="registry-docs"><h2>Linked governance layer</h2><p>Official instruments, temporal status, five complete provision dimensions and typed associations to existing systems. The system registry is unchanged.</p><Link className="btn" href="/governance">Inspect governance data and downloads</Link></section>
    <section className="registry-docs"><h2>Scaling round: 72 additional system families</h2><p>Public banking, nutrition and housing, court assistance, education, state service delivery, environmental warning, government infrastructure and public-sector capabilities. Proposed, historical and enabling units are labelled; this is not a claim of 144 independently verified live AI deployments.</p><div className="registry-downloads"><DownloadFile file="SCALING_STUDY.md">Latest study: all 72 additions</DownloadFile><DownloadFile file="SCALING_SEARCH.json">Scaling research query log</DownloadFile><DownloadFile file="SCALING_RETRIEVAL.json">Retrievals and recovery receipts</DownloadFile><DownloadFile file="SCALING_QUOTE_AUDIT.json">Selected-excerpt provenance checks</DownloadFile><DownloadFile file="BASELINE_1_2_0.json">All prior-row preservation checksums</DownloadFile></div><p className="fine">Cached recovery and fresh requests are distinguished in source metadata. A successful text fetch is not proof of current operation or independent review.</p></section>
    <section className="registry-docs"><h2>Earlier broadening round: 36 additional named services</h2><p>Identity, pensions, grievances, telecom risk, securities regulation, agriculture, roads, water, clinical research and defence decision support. This purposive cohort is not another complete ministry inventory. Legacy apps, installations and internal channels are not inflated into extra systems.</p><div className="registry-downloads"><DownloadFile file="BROADENING_STUDY.md">Earlier research and all 36 additions</DownloadFile><DownloadFile file="BROADENING_SEARCH.json">153-query broadening log</DownloadFile><DownloadFile file="BROADENING_RETRIEVAL.json">100 retrieval receipts</DownloadFile><DownloadFile file="BROADENING_QUOTE_AUDIT.json">49-source excerpt check</DownloadFile><DownloadFile file="BASELINE_1_1_0.json">Earlier preservation checksums</DownloadFile></div></section>
    <section className="registry-docs"><h2>Original fixed institutional coverage frame</h2><p>Four comparable searches per institution covered deployment, procurement, safeguards/evaluation and recency in the earlier round. Its 26-record cohort remains separate from the broadening additions. These are completed search procedures, not complete administrative inventories. The Supreme Court is an independent institution, not a ministry-owned judiciary.</p><div className="registry-table-downloads">{data.institution_coverage.map((f:Row)=><div key={f.frame_id}><div><b>{f.institution_name}</b><p>{data.coverage_systems.filter((r:Row)=>r.frame_id===f.frame_id).length} associated system records · {f.scope}</p></div></div>)}</div><div className="registry-downloads"><DownloadFile file="INSTITUTION_STUDY.md">Earlier institutional study</DownloadFile><DownloadFile file="INSTITUTION_SEARCH.json">36-query second-round log</DownloadFile><DownloadFile file="INSTITUTION_RETRIEVAL.json">Second-round retrieval receipts</DownloadFile><DownloadFile file="SOURCE_RECHECK.json">Original-baseline source recheck</DownloadFile></div><p className="fine">Re-fetching and text matching are not independent recoding. A cookie banner, parser mismatch or inaccessible PDF is not proof a source claim was withdrawn.</p></section>
    <section className="registry-docs"><h2>Start with the method, then the findings</h2><div className="registry-downloads"><DownloadFile file="RESEARCH_NOTE.md">Research note and findings</DownloadFile><DownloadFile file="PROTOCOL.md">Collection and coding protocol</DownloadFile><DownloadFile file="CODEBOOK.md">Full data codebook</DownloadFile><DownloadFile file="queries.sql">Runnable SQL examples</DownloadFile></div><p className="fine">Reproduction validates the curated release, not the truth of an agency claim. A second independent reviewer has not yet coded this seed.</p></section>
    <section className="registry-docs"><h2>Machine-readable release</h2><div className="registry-downloads"><DownloadFile file="data.json">Complete JSON</DownloadFile><DownloadFile file="dataset.sqlite">SQLite database</DownloadFile><DownloadFile file="schema.json">Column schema</DownloadFile><DownloadFile file="manifest.json">File inventory and hashes</DownloadFile><DownloadFile file="manifest.sha256">Manifest checksum</DownloadFile><DownloadFile file="analysis.json">Reproducible corpus counts</DownloadFile></div></section>
    <section className="registry-docs"><h2>All linked tables</h2><p>First column is the primary key. Use evidence_links to join each claim or observation to excerpts and original sources; never count evidence links as systems.</p><div className="registry-table-downloads">{tables.map(t=><div key={t}><div><b>{t.replaceAll('_',' ')}</b><p>{data.metadata.counts[t]} records</p></div><DownloadFile file={`${t}.csv`}>CSV</DownloadFile></div>)}</div></section>
    <section className="registry-docs"><h2>Research receipts and exclusions</h2><div className="registry-downloads"><DownloadFile file="search-log.json">Original 62-query seed log</DownloadFile><DownloadFile file="retrieval-log.json">Original retrievals and blocked records</DownloadFile><DownloadFile file="candidate_decisions.csv">Selection and exclusion decisions</DownloadFile></div><p>Search snippets are leads, not substantive evidence. Unretrieved annual reports and training PDFs remain unreviewed. Full copyrighted papers and original PDF binaries are not mirrored.</p></section>
    <section className="registry-docs"><h2>Source catalogue</h2><p>Dates come from reviewed documents where established; null stays null. Government-hosted vendor material is not independent validation. Hashes cover selected excerpt snapshots, not original PDFs.</p><div className="registry-source-list">{data.sources.map(s=><details key={s.source_id}><summary>{s.title}</summary><p>{s.source_type} · {s.published_date||'Undated / uncertain'}<br/>{s.date_basis}<br/>Recheck: {data.source_rechecks.find((r:Row)=>r.source_id===s.source_id)?.status||'New source: selected excerpts checked against fetched text'}</p><p className="fine">{s.snapshot_sha256}</p><a className="text-link" href={s.url} target="_blank" rel="noreferrer">Original record <ExternalLink size={14}/></a> <a className="text-link" href={`./registry/${s.snapshot}`} download>Selected excerpts</a></details>)}</div></section>
    <footer className="registry-footer"><p>No live nationwide monitoring, personal records or automatic external enquiries. Source-linked unknowns are a research queue, not proof of wrongdoing.</p><Link className="text-link" href="/data">Earlier policy corpus archive <ArrowRight size={14}/></Link></footer>
  </div>
}
